import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;


//Class for generate the Name of the file
public class FileNameGenerator {

    public static String getSamepleName(int eventNumber, int sampleNumber)
    {
        String name = "E" + eventNumber + "S" +sampleNumber;
        return name+".txt";
    }

    public static String getPatternName(int eventNumber)
    {
        String name = "E" + eventNumber + "pattern";
        return name+".txt";
    }


    //return the name of sample by time
    public static String getWaveSampleName() {

        //part for generating the file name with time based on it
        String time;
        String name = "sample_";
        Date date = Calendar.getInstance().getTime();
        SimpleDateFormat formatter = new SimpleDateFormat("yyMMddhhmmss");
        time = formatter.format(date);
        name += time;
        name = name.concat(".wav");
        return name;
    }

    
    //Generated By Time
    public static String getTextSampleName() {
        //part for generating the file name with time based on it
        String time;
        String name = "sample_";
        Date date = Calendar.getInstance().getTime();
        SimpleDateFormat formatter = new SimpleDateFormat("yyMMddhhmmss");
        time = formatter.format(date);
        name += time;
        name = name.concat(".txt");
        return name;
    }

}
